 const films = [
  {
    "Title": "Moi brat Betmen",
    "Year": "2015",
    "Rated": "N/A",
    "Released": "N/A",
    "Runtime": "N/A",
    "Genre": "Short",
    "Director": "Tatyana Rakhmanova",
    "Writer": "N/A",
    "Actors": "Ivan Nikolaev",
    "Plot": "N/A",
    "Language": "Russian",
    "Country": "Russia",
    "Awards": "N/A",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMjliYmZiOWEtYjFjZS00ZjRkLThlZmItY2NjODgzYjgzMTYyXkEyXkFqcGdeQXVyODg3MTQ1NDk@._V1_SX300.jpg",
    "Ratings": [],
    "Metascore": "N/A",
    "imdbRating": "N/A",
    "imdbVotes": "N/A",
    "imdbID": "tt8675456",
    "Type": "movie",
    "DVD": "N/A",
    "BoxOffice": "N/A",
    "Production": "N/A",
    "Website": "N/A",
    "Response": "True"
  },
  {
    "Title": "Spider Man: Lost Cause",
    "Year": "2014",
    "Rated": "N/A",
    "Released": "26 Sep 2014",
    "Runtime": "140 min",
    "Genre": "Action, Adventure, Comedy",
    "Director": "Joey Lever",
    "Writer": "Steve Ditko, Stan Lee, Joey Lever",
    "Actors": "Joey Lever, Craig Ellis, Teravis Ward",
    "Plot": "Peter Parker a lone child discovers that his parents were in a horrifying plot to make mankind change. getting bitten by his fathers invention he develops super powers to tries to find answers to his whole life, try and juggle a r...",
    "Language": "English",
    "Country": "United Kingdom",
    "Awards": "N/A",
    "Poster": "https://m.media-amazon.com/images/M/MV5BYmZkYWRlNWQtOGY0Zi00MWZkLWJiZTktNjRjMDY4MTU2YzAyXkEyXkFqcGdeQXVyMzYzNzc1NjY@._V1_SX300.jpg",
    "Ratings": [{ "Source": "Internet Movie Database", "Value": "4.5/10" }],
    "Metascore": "N/A",
    "imdbRating": "4.5",
    "imdbVotes": "440",
    "imdbID": "tt2803854",
    "Type": "movie",
    "DVD": "N/A",
    "BoxOffice": "N/A",
    "Production": "N/A",
    "Website": "N/A",
    "Response": "True"
  },
  {
    "Title": "Robokop",
    "Year": "1996",
    "Rated": "N/A",
    "Released": "N/A",
    "Runtime": "3 min",
    "Genre": "Short",
    "Director": "Michael Ray Fox",
    "Writer": "Michael Ray Fox",
    "Actors": "N/A",
    "Plot": "Hilarious re-imagining of the 1987 film \"Robocop\" made entirely with claymation on Super 8 film by 12-year old filmmaker Michael Ray Fox.",
    "Language": "English",
    "Country": "Canada",
    "Awards": "N/A",
    "Poster": "N/A",
    "Ratings": [{ "Source": "Internet Movie Database", "Value": "8.7/10" }],
    "Metascore": "N/A",
    "imdbRating": "8.7",
    "imdbVotes": "7",
    "imdbID": "tt1965044",
    "Type": "movie",
    "DVD": "N/A",
    "BoxOffice": "N/A",
    "Production": "N/A",
    "Website": "N/A",
    "Response": "True"
  },
  {
    "Title": "Matrix",
    "Year": "1993",
    "Rated": "N/A",
    "Released": "01 Mar 1993",
    "Runtime": "60 min",
    "Genre": "Action, Drama, Fantasy",
    "Director": "N/A",
    "Writer": "Grenville Case",
    "Actors": "Nick Mancuso, Phillip Jarrett, Carrie-Anne Moss",
    "Plot": "Steven Matrix is one of the underworld's foremost hitmen until his luck runs out, and someone puts a contract out on him. Shot in the forehead by a .22 pistol, Matrix \"dies\" and finds himself in \"The City In Between\", where he is ...",
    "Language": "English",
    "Country": "Canada",
    "Awards": "1 win",
    "Poster": "https://m.media-amazon.com/images/M/MV5BYzUzOTA5ZTMtMTdlZS00MmQ5LWFmNjEtMjE5MTczN2RjNjE3XkEyXkFqcGdeQXVyNTc2ODIyMzY@._V1_SX300.jpg",
    "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.7/10" }],
    "Metascore": "N/A",
    "imdbRating": "7.7",
    "imdbVotes": "196",
    "imdbID": "tt0106062",
    "Type": "series",
    "totalSeasons": "N/A",
    "Response": "True"
  },
  {
    "Title": "Terminator",
    "Year": "1991",
    "Rated": "N/A",
    "Released": "N/A",
    "Runtime": "39 min",
    "Genre": "Short, Action, Sci-Fi",
    "Director": "Ben Hernandez",
    "Writer": "James Cameron, Ben Hernandez",
    "Actors": "Loris Basso, James Callahan, Debbie Medows",
    "Plot": "A cyborg comes from the future, to kill a girl named Sarah Lee.",
    "Language": "English",
    "Country": "United States",
    "Awards": "N/A",
    "Poster": "N/A",
    "Ratings": [{ "Source": "Internet Movie Database", "Value": "6.1/10" }],
    "Metascore": "N/A",
    "imdbRating": "6.1",
    "imdbVotes": "39",
    "imdbID": "tt5817168",
    "Type": "movie",
    "DVD": "N/A",
    "BoxOffice": "N/A",
    "Production": "N/A",
    "Website": "N/A",
    "Response": "True"
  }
]

export default films